### ISSUE TITLE
Question requirements.txt does not include jupyter or jupyter lab

### ISSUE THREAD

**Issue by jake-aft** [DerwenAI/kglab#1]
Happy Monday Paco,

The requirements.txt does not include jupyter or jupyter-lab is that intentional?

**Comment by ceteri** [comment]
Good point, thanks!  We need to add instructions about running JupyerLab https://jupyter.org/install too.

I'd originally planned to use Google Colab, although it's not particularly friendly toward installing some of the libraries correctly, such as `rdflib` -- so we'll ask people to clone the repo locally and run JupyterLab.

**Comment by ceteri** [comment]
resolved in #2
