### ISSUE TITLE
directions for RDBMS support in general

### ISSUE THREAD

**Issue by ceteri** [DerwenAI/kglab#108]
Following up after some work with [Trino](https://github.com/trinodb/trino) authors yesterday, there are needs ahead for better metadata modeling based on inference techniques, semantic technologies, etc., for example in [Iceberg](https://github.com/apache/iceberg) connectors.

Just found this about *Morph-RDB* :

- <http://www.semantic-web-journal.net/system/files/swj2619.pdf>
- <https://morph.oeg.fi.upm.es/tool/morph-rdb>
- <https://github.com/oeg-upm/morph-rdb/>

Probably a good thing to have a spike toward: how to integrate with Trino and Morph-RDB.  Will check with @dachafra, et al.

Could be good to discuss with @dvsrepo and Asun about this, too?  It could become an integration point for Recognai?

**Comment by dachafra** [comment]
@ceteri we are currently developing a new python-based engine that could fit better than Morph-RDB  (java-based), and it is also able to parse RML and R2RML mappings. It's currently under review so it's not public yet, but it will be soon. @ArenasGuerreroJulian and I will be really happy to help in the integration.

**Comment by ArenasGuerreroJulian** [comment]
Hi @ceteri we have released [Morph-KGC](https://github.com/oeg-upm/morph-kgc) if it is useful

**Comment by ceteri** [comment]
Hi @ArenasGuerreroJulian @dachafra thank you, this is great to see! We're beginning integration of `morph-kgc` with `kglab` now, and have a potential large use case in industry at BASF. I'm working with @paoespinozarias @neobernad @jelisf @jmueller5 on the integration.  There may be ways we can collaborate on parallelization, e.g., with Ray, Dask, etc. ?

**Comment by Mec-iS** [comment]
happy to help when implementation guidelines are available

**Comment by ArenasGuerreroJulian** [comment]
Hi @ceteri awesome! `morph-kgc` already parallelizes using `multiprocessing` library. I am exploring further parallelization with `Dask`, happy to collaborate

**Comment by ceteri** [comment]
@ArenasGuerreroJulian that's excellent. We're using Ray in the production environment to scale out graphs, and in Ray there's a drop-in replacement for the standard `multiprocessing` library: https://github.com/DerwenAI/ray_tutorial/blob/main/ex_04_mult_pool.ipynb

**Comment by ceteri** [comment]
@Mec-iS how about this approach:

- add `morph-kgc` into project dependencies
- add a `.materialize()` method to the `kglab.KnowledgeGraph()` which takes an `.ini` file as its parameter
- merge the graph materialized by Morph with the `KnowledgeGraph._g` graph
   -  could be based on https://rdflib.readthedocs.io/en/stable/merging.html via serialization of one graph?
   - or iterate items of one graph to add to the other?

For testing, we could use a CSV file as the input.

Does that seem like a good approach for integration?

**Comment by ceteri** [comment]
Many thanks @Mec-iS @ArenasGuerreroJulian @dachafra !
