### ISSUE TITLE
Leiden alg example doesn't work; missing recipes.ttl 

### ISSUE THREAD

**Issue by iblind** [DerwenAI/kglab#204]
`kg.load_rdf("../dat/recipes.ttl")` doesn't seem to load the recipes when following the tutorial at https://derwen.ai/docs/kgl/ex6_1/

Where would I be able to find this file?

**Comment by Mec-iS** [comment]
please specify which operating system you are using.
All the static files used in notebooks are in the `dat/` directory in the project's main directory.

should be fixed by #205

**Comment by Mec-iS** [comment]
I guess we can close this one?

**Comment by iblind** [comment]
Hey there, I'm on MacOS 11.6 — I'll check whether this works for me later today!

**Comment by iblind** [comment]
Looks like it's working on my end, thanks @Mec-iS and @ceteri

**Comment by ceteri** [comment]
So glad to hear @iblind !
