### ISSUE TITLE
Improve SPARQL tests

### ISSUE THREAD

**Issue by Mec-iS** [DerwenAI/kglab#248]
As per conversation.

https://github.com/oxigraph/oxrdflib/issues/8#issuecomment-1076838034

**Comment by Mec-iS** [comment]
`oxigraph` implements an automatic test suite that pulls examples from W3C and test them against its architecture.

The files involved are (some examples to be found [here](https://w3c.github.io/rdf-star/tests/sparql/eval/manifest#sparql-star-results-1j)):
* `.rq` file to define the query
* `.ttl` file to define the data in the graph
* `.srj` file to define the expected output

We can create a testsuite that use this files to load the data, run the query and compare the results.

**Comment by ceteri** [comment]
Excellent, that's great @Mec-iS !

Also, we can instrument for performance analysis when running these SPARQL test suite features:
  - timing (`time.time()`)
  - statistical call stack trace (`pyinstrument`)
  - memory high-water mark (`tracemalloc`)
  - memory leak analysis (`objgraph`)

For example, these get performed in <https://github.com/DerwenAI/ray_tutorial/blob/main/pi.ipynb>

This will become especially important when we're working with the NVIDIA-basd GPU optimizations for `kglab`

**Comment by Tpt** [comment]
Thank you! The SPARQL W3C test suite format seems indeed to be the best. It is implementation independant and a lot of systems implement it like [rdflib](https://github.com/RDFLib/rdflib/blob/03c5e79298b35f29087ff82002becaaba0e3a656/test/test_dawg.py#L1), [Jena](https://github.com/apache/jena/blob/6e4837ee51f7c1a7bc3dfa18a21abd4c3f94d1bb/jena-arq/README.txt#L76), [RDF4J](https://github.com/eclipse/rdf4j/tree/main/testsuites/sparql/src/main/resources), [ruby-rdf](https://github.com/ruby-rdf/sparql/blob/3def7ce58202f698ca02c800944d89a7b4fa42e2/script/tc), [sparql-ex](https://github.com/rdf-elixir/sparql-ex/tree/master/test) and [Communica](https://www.npmjs.com/package/rdf-test-suite). So, all the efforts done here could be reused to test other systems.

About instrumentation, if we instrument from Python we would need to use tools able to instrument native code too. Oxigraph is implemented in Rust and only the rdflib wrapper is in Python. Oxigraph already uses [LLVM AddressSantizer](https://clang.llvm.org/docs/AddressSanitizer.html) to fight memory errors and leaks and [Criterion](https://bheisler.github.io/criterion.rs/book/index.html) for speed benchmarking. I personally use [the Clion profiler](https://www.jetbrains.com/help/clion/cpu-profiler.html) to do profiling but something that could be publicly shared would be much better.

**Comment by Mec-iS** [comment]
#253

**Comment by Mec-iS** [comment]
@Tpt I am running into this error when passing query results into the `bindingsCompatible` function:
```
TypeError: unsupported operand type(s) for -: 'RDFResult' and 'set'
```
It seems that the tests return sometimes return `RDFResult` that cannot be cast into a set. For example test `bound/dawg-bound-query-001`. Any hint? Thanks

**Comment by Tpt** [comment]
@Mec-iS I believe it's because the `bindingsCompatible` expect its arguments to be sets and [where it is called](https://github.com/DerwenAI/kglab/blob/c9116f0ba22bb2f82490dc8da41ceecb8c674e6d/tests/rdf_tests/test_rdf_basic.py#L158) the arguments are not cast into sets opposite to [what rdflib does](https://github.com/RDFLib/rdflib/blob/a347f8d548e452d03e45f7d7b6b59a36e9d047f4/test/test_dawg.py#L437).

**Comment by VladimirAlexiev** [comment]
The folders `basic` and `algebra` in https://github.com/DerwenAI/kglab/tree/main/tests/rdf_tests/dat contain obsolete SPARQL 1.0 tests, see eg http://rawgit2.com/DerwenAI/kglab/main/tests/rdf_tests/dat/algebra/index.html.
Please use the official W3C SPARQL tests.

Test runner: if you're willing to use PHP, there is https://github.com/BorderCloud/TFT that powers http://sparqlscore.com/

**Comment by Mec-iS** [comment]
@VladimirAlexiev thanks for your comment

Are all the tests in `basic` and `algebra` in the `data-r2` deprecated? Should we use only the ones in `sparql11` directory instead?

**Comment by Mec-iS** [comment]
after a closer look, there were already `sparql11` tests running but the directory structure is flattened between sparql1 and sparql11 rdf-tests.

I have added more sparql11 tests #259

**Comment by Mec-iS** [comment]
moved to #250
