### ISSUE TITLE
Move setup.py functionality to poetry for pre-check and package build and release.

### ISSUE THREAD

**Issue by jake-biolexis** [DerwenAI/kglab#275]
### I'm submitting a 
 [x] feature idea to research and discuss

This is split from https://github.com/DerwenAI/kglab/issues/272 

### Current Behaviour:
Investigate and review the implication of changing the existing use of setup.py and using poetry instead for pre-check, package build, and release.

One thing I am not at all clear on is the documentation building for KGLab, and how that will need to be managed in a poetry env / process.

**Comment by ceteri** [comment]
hi @jake-biolexis ,
i'm doing an initial impl on `pyproject.toml` since it will be required for the next update of `pip`

my impl could probably use some help :)

**Comment by jake-aft** [comment]
@ceteri i do not have permission to publish to test-pipy on kglab.

using poetry build

I am getting builds at ~50 K with exclude. That seems quite small ?
➜  kglab git:(poetry_build) ✗ ls -lh dist                                                                                                                                    
-rw-r--r--  1 jake  staff    51K Dec  3 16:35 kglab-0.1.1a3-py3-none-any.whl
-rw-r--r--  1 jake  staff    45K Dec  3 16:35 kglab-0.1.1a3.tar.gz

**Comment by jake-aft** [comment]
#### Included in PR - https://github.com/DerwenAI/kglab/pull/300
