### ISSUE TITLE
Discuss graph sizes

### ISSUE THREAD

**Issue by ceteri** [DerwenAI/kglab#28]
Discuss at an early point within the sequence of notebooks whether this is merely a "trivial" example or not.

  * dataset provides a simple example, leading up to ~250K recipes for a non-trivial graph
  * the medium-sized has ~200 nodes
    * large enough for examples to illustrate common use cases
    * small enough for learners to understand
  * NB: any graph with over 1K elements can be non-trivial
  * 10^6 or more needed for deep learning
  * 10^8 can run fine on contemporary laptops without hardware accelerators or cloud-based clusters

**Comment by dmoore247** [comment]
?Elements owl:sameAs ?triples ?

**Comment by ceteri** [comment]
> ?Elements owl:sameAs ?triples ?

That's a good point.  Instead, as a rough estimate, `elements` is intended to equal `# nodes`
