### ISSUE TITLE
Missing direction of edges in visualisation example

### ISSUE THREAD

**Issue by akuckartz** [DerwenAI/kglab#307]
### I'm submitting a 
- [x] bug report.
- [x] feature request.

### Current Behaviour:
I am experimenting with the example code in section "Graph visualization with kglab using subgraphs" of the tutorial
https://derwen.ai/docs/kgl/ex3_0/

So far I have not managed to see directed edges with arrows. None of the edges contain any indication of direction in the visualisation.

### Expected Behaviour:
The example visualisation should contain directed edges with arrows.

### Steps to reproduce:
Just follow the instructions in the tutorial.
https://derwen.ai/docs/kgl/ex3_0/

### Environment:
* python version 3.11.2
* pip version 23.0.1
* Microsoft Windows 10 with Microsoft Edge

**Comment by ceteri** [comment]
Thank you @akuckartz for the feedback.

The 3.0 section of the tutorial shows `pyvis` visualizing a simple example of an _undirected_ graph. What is shown is correct behavior, with no arrows that should be drawn.

We have other examples involving _directed graphs_ which show visualizations with directed edges and arrows drawn, such as in <https://derwen.ai/docs/kgl/ex6_0/>

If you want to use `pyvis` to visualize directed graphs, that simply requires setting the `to` and `from` keyword parameters when calling the `add_edge()` method: <https://pyvis.readthedocs.io/en/latest/documentation.html?highlight=directed#pyvis.network.Network.add_edge>

**Comment by akuckartz** [comment]
@ceteri Thanks for the reply.

Edges in RDF graphs _are_ directed. There is therefore a mismatch between my expectation and the `pyvis` example. I expected that there exists a simple way to modify the example so that it produces a directed graph with arrows. Maybe with a parameter such as `Directed = True`.

The `NetworkX` example does not really help here because I did not want to write a significant amount of new code just to add the arrows. I am also not sure that `NetworkX` supports edge-labels as `pyvis` does.

**Comment by ceteri** [comment]
@akuckartz this project is intended for integration of several graph-related libraries. If you want to use those libraries, in turn, then you should study their capabilities, features, and interfaces. It is clear that you have not, nor are you likely to do so.

**Comment by akuckartz** [comment]
> ... nor are you likely to do so.

:-/

**Comment by akuckartz** [comment]
@ceteri Please reopen this issue. Thanks.

It is very easy to modify the first example on the page (below the headline "Interactive graph visualization with pyvis") so that arrows are shown. To do that one can simply replace
> pyvis_graph = pyvis.network.Network(notebook=True)

with

> pyvis_graph = pyvis.network.Network(notebook=True, directed=True)

But my issue is about the second example (below the headline "Graph visualization with kglab using subgraphs"). No such modification is possible for this example because this requires a (probably rather simple) modification within kglab.

What I found out so far is that likely the implementation of `build_pyvis_graph(...)` in `subg.py` needs to be modified so that `directed=True` can be passed as a parameter to `pyvis.network.Network(...)`. Maybe I can provide a patch but you probably know better how to best improve that part of the code.
