### ISSUE TITLE
Custom memory store

### ISSUE THREAD

**Issue by ceteri** [DerwenAI/kglab#37]
Develop a custom store for `kglab` based on the [`Memory`](https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.plugins.html#rdflib.plugins.memory.IOMemory) store plugin:

  * future support for extensions to N-Quads based on `Parquet`
  * future support distributed stores (*sharding*) based on `Ray`
  * enhanced use of GPU hardware accelerators based on `RAPIDS`

**Comment by dmoore247** [comment]
Interested in your vision here, are we thinking tiers of storage, predicate pushdown, query planning etc.
