### ISSUE TITLE
Integrate with Snorkel for weak supervision use cases

### ISSUE THREAD

**Issue by ceteri** [DerwenAI/kglab#41]
Integrate with [Snorkel](https://www.snorkel.org/) for *weak supervision* use cases

  * add  a notebook to show use of *weak supervision* as a complement to PSL, KGE, etc.
  * enhance the semantic tagging of the 14K ingredients in the full dataset for the recipe KG

**Comment by ceteri** [comment]
While we're at this spike on *weak supervision* we should probably also go the extra step to integrate [`human-learn`](https://koaning.github.io/human-learn/) as an alternative approach for first-pass on a large set of annotations.

In other words, guid learners to build an HITL feedback loop that leverages PSL, KGE, Shape Prediction, etc., to get coverage on a much of the unlabeled cases as possible.

Eager to get this into `spaCy` pipeline through `pytextrank` integration.

Best case scenario: run `scikit-learn` pipelines in `lale` to leverage `human-learn`, `snorkel`, etc.
For example, see:

  * <https://gist.github.com/Mageswaran1989/1197796d81674444391b25074f79b989>

Might be useful to have a conversation with @koaning

**Comment by koaning** [comment]
AskMeAnything[tm]

That said, I'm also working on some bulk labeling tools at the moment. The idea is to build ipywidgets that can be combined in a lot of ways. I'm not 100% certain where they'll land. It might be human-learn but I might put them on another project. Human-learn is more meant for tabular data and scikit-learn pipelines.

**Comment by ceteri** [comment]
Many thanks @koaning, I'll keep a watch on [`human-learn`](https://github.com/koaning/human-learn/) as this evolves.

And definitely, what we're trying to do with `kglab` is make other graph libraries easier to use as parts of pipelines that involve `pandas`, `scikit-learn`, `spaCy`, etc.

**Comment by ceteri** [comment]
Along with `snorkel` above, it could be helpful to evaluation an integration with `hover` https://lnkd.in/g3ycUrH

**Comment by ceteri** [comment]
Much more _weak supervision_ is available on https://github.com/recognai/rubrix
plus, this intended use case was more about data labeling (linking data into a graph) and fits better in specific labeling libraries.
