### ISSUE TITLE
AttributeError: module 'kglab' has no attribute 'Subgraph'

### ISSUE THREAD

**Issue by trickidicki** [DerwenAI/kglab#72]
Working through some of the tutorials and finding problems:
```
subgraph = kglab.Subgraph(kg)
AttributeError: module 'kglab' has no attribute 'Subgraph'
```
and

```
measure = kglab.Measure()
AttributeError: module 'kglab' has no attribute 'Measure'
```

Windows 10, Python 3.8.3 (64 bit), numpy==1.19.0

**Comment by ceteri** [comment]
Thank you @trickidicki 

I have a hunch you were using a mix of the `pip install kglab` for v0.1.4 and then example code on `main` branch of the GitHub repo?  You caught this just before a release was pushed :)

Try updating to the v0.1.5 release <https://pypi.org/project/kglab/> and use of those new classes `Subgraph` and `Measure` should work fine now.  If not, please let us know!
