### ISSUE TITLE
Integration with Graph DBs

### ISSUE THREAD

**Issue by ceteri** [DerwenAI/kglab#76]
Provide integration paths for popular graph databases.
Based on our user survey, the priorities are:

- neo4j
- DataStax
- Ontotext
- etc.

**Comment by ceteri** [comment]
One integration path for neo4j would be to export:

 - as RDF: <https://neo4j.com/docs/labs/nsmntx/current/export/>
 - as GraphML: <https://neo4j.com/labs/apoc/4.1/export/graphml/>

**Comment by gauravjaglan** [comment]
For Neo4J, I will be creating python interface for kglab. Steps would be:
1. Authentication with the running Neo4J server
2. Work with RDF export for existing triples.( check feasibility of directly fetching data from Neo4J rather than generating importable ttl files.)

**Comment by ceteri** [comment]
Awesome @gauravjaglan! This is trending as one of the top requests for graph DB integration, within our ongoing feature survey: <https://forms.gle/ufM1DQ2ktVpuYJ6C6>

**Comment by gauravjaglan** [comment]
@ceteri can you check integration with Neo4J. I have tested the code several times. Check if anything is required. I am on my way to Blazegraph now.

**Comment by ceteri** [comment]
Thank you @gauravjaglan -
Is this the branch and code module here? <https://github.com/gauravjaglan/kglab/blob/gauravjaglan-external_integration-1/kglab/external_import.py>

Looks good!  I see the sample usage too.

One question: what's a simple way to set up a neo4j instance which with we can test this?

That will be very helpful for testing, documentation, and tutorial.

Also, there's no open pull request on either of the branches on <https://github.com/DerwenAI/kglab>
Just wanted to make sure, in case you were seeing a PR?

**Comment by ceteri** [comment]
created a pull request #124

**Comment by gauravjaglan** [comment]
Hello @ceteri, I have started with ontotext's graphDB and Blazegraph.

**Comment by ceteri** [comment]
Awesome, thankyou @gauravjaglan !

**Comment by kaaloo** [comment]
My wish list 😉 

- [TerminusDB](https://github.com/terminusdb/terminusdb) Open source graph database and document store. Designed for collaboratively building data-intensive applications and knowledge graphs. Really cool rust triple store and prolog api and query engine.
- [Weaviate](https://github.com/semi-technologies/weaviate) A cloud-native, modular, real-time vector search engine.  Uses a cool custom HNSW k-NN algorithm.
- [Dgraph](https://github.com/dgraph-io/dgraph) Native GraphQL Database with graph backend. Designed for scalability.

**Comment by ceteri** [comment]
Excellent, thank you @kaaloo !
