### ISSUE TITLE
add a multifile decorator for the serialization methods

### ISSUE THREAD

**Issue by ceteri** [DerwenAI/kglab#91]
Add a `@multifile` decorator for handling paths with wildcards, in each of the serialization methods.

For a great example, see <https://github.com/koaning/clumper/blob/master/clumper/decorators.py>

**Comment by Ankush-Chander** [comment]
Hi @ceteri,

I checked out the [given example](https://github.com/koaning/clumper/blob/master/clumper/decorators.py) which led me to conclude that the desired outcome here is that all load_* type methods in kglab.py should accept wildcards in the path and generate  KnowlegeGraph by reading all the files that satisfy the wildcard expression.
Please let me know if I understood the requirement right.

Thanks in advance.

**Comment by ceteri** [comment]
Thank you @Ankush-Chander !

Yes, the intent is to add a `@multifile` decorator to the methods:

- `load_rdf()`
- `load_jsonld()`
- `load_parquet()`

Although the `load_csv()` method has other work going into restructuring it, and that should be skipped for now.

One caveat is that the example code in <https://github.com/koaning/clumper> has some understanding about checking for string-based paths vs. `glob.glob` vs. `pathlib.Path` – and I >think< that will fit here just fine.

Each of these three methods has internal consistency checks for the path arguments at runtime. I believe that those should not need to be reworked -- unless any issues come up.

Background: within `kglab` we're trying to standardize on the `pathlib.Path` approach whenever possible. This is important for some of our next steps in integration and parallelizing large units of work. For example, one practice that's common in data engineering is to store large datasets in Parquet partitions -- e.g., with a specified S3 bucket, each of the files is one Parquet partition, so then an ETL process can be parallelized using Spark, either for read or write.  We're planning to parallelize the `rdflib.Storage` class with Ray later, and it will be important to point at a bucket (or another kind of storage grid endpoint) with a team's access credentials, then be able to enumerate a set of Parquet "file names" for the worker processes to each use.  By using `pathlib.Path` to represent path info, then some of its available subclasses like `urlpath` can be leveraged. Also there are other ways that our libraries are working with `fsspec`, `gcsfs`, etc., for similar purposes.

Does that help describe the requirement and give background?

**Comment by Ankush-Chander** [comment]
Thank you @ceteri. 
That"s a pretty clear picture of what we want to achieve here. I am on it.

**Comment by ceteri** [comment]
This is looking good!

I had to refactor the unit test, since `kglab` is still using `unittest` not `pytest` (and should upgrade!! :) )
Also, to get through the pre-commit hooks.

Nice work!
