### ISSUE TITLE
Error in installation

### ISSUE THREAD

**Issue by pramitchoudhary** [DerwenAI/kglab#94]
python 3.7
OS: Ubuntu 18.0.4
Not sure, if related to `gcc` version.
```
Building igraph...
    make  all-recursive
    make[1]: Entering directory '/tmp/pip-build-c1_k87ni/python-igraph/vendor/build/igraph'
    Making all in src
    make[2]: Entering directory '/tmp/pip-build-c1_k87ni/python-igraph/vendor/build/igraph/src'
      YACC     foreign-ncol-parser.c
    ../../../source/igraph/ylwrap: line 176: yacc: command not found
    Makefile:9045: recipe for target 'foreign-ncol-parser.c' failed
    make[2]: *** [foreign-ncol-parser.c] Error 127
    make[2]: Leaving directory '/tmp/pip-build-c1_k87ni/python-igraph/vendor/build/igraph/src'
    Makefile:497: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/tmp/pip-build-c1_k87ni/python-igraph/vendor/build/igraph'
    Makefile:404: recipe for target 'all' failed
    make: *** [all] Error 2
    Could not compile the C core of igraph.


    ----------------------------------------
Command "/venv/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-c1_k87ni/python-igraph/setup.py';f=getattr(tokenize, 'open', open)(__file__);c
ode=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-8b7gbk46-record/install-record.txt --single-version-externally-managed --compile --install-headers
 ./venv/include/site/python3.7/python-igraph" failed with error code 1 in /tmp/pip-build-c1_k87ni/python-igraph/
```

**Comment by ceteri** [comment]
Thank you @pramitchoudhary !!

This has already helped me understanding some very odd interactions on Ubuntu 18.0.4 between `cython`, Py 3.7, and `pandas` 1.2.0 – there may be other dependencies that weren't understood before.

When you were installing **kglab**, which approach did you use?

- `pip install kglab`
- git clone, then `python setup.py install`
- git clone, then `pip install -r requirements.txt`

That info may help me track down the issue.

Otherwise, it may be back to back out of the latest `pandas` until that's more stable on Ubuntu.  I was hopeful, since the new integration with `pyarrow` is super useful, although there are some good workarounds! :)

**Comment by ceteri** [comment]
Also, I should note:
The issue with `cython` that I encountered on Ubuntu was
> RuntimeError: Cannot cythonize with old Cython version (0.29.16 installed, needs 0.29.21)

Although even after updating the `cython` release, there were still problems attempting to install `pandas` 1.2.0 on Ubuntu.  Will continue working on that.

**Comment by ceteri** [comment]
@pramitchoudhary, 
I just tried experimenting with an Ubuntu 18.0.4 LTS, freshly launched on GCP with the following:

- Python 3.6.9
- GCC 8.4.0
- added `sudo apt-get install python3-pandas`

The `python-igraph` dependency seems to install fine, even for the `0.8.3` release that's in **kglab** `requirements.txt`:

```
$ pip install python-igraph
Collecting python-igraph
  Downloading python_igraph-0.8.3-cp36-cp36m-manylinux2010_x86_64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 7.7 MB/s 
Collecting texttable>=1.6.2
  Downloading texttable-1.6.3-py2.py3-none-any.whl (10 kB)
Installing collected packages: texttable, python-igraph
Successfully installed python-igraph-0.8.3 texttable-1.6.3
```

However, I'm finding out that `pandas` 1.2.0 is not going to work yet for Ubuntu.  

I'll back out that dependency (just requires a couple explicit calls to `pyarrow`, no prob) then push a new point release up to PyPi

**Comment by ceteri** [comment]
The release 1.6.0 installs and passes unit tests on Ubuntu 18.0.4 LTS now.

Best to install the package via PyPi `pip` and not by using `python setup.py install` on the repo directly.  Some of the dependencies are a bit flaky in how they handle versioning, and that seems to interact on Ubuntu if:

- GCC is an older release
- `setuptools` is an older release
- Moon is full on a Thursday, etc.

However, the packages built on PyPi appear to work on a vanilla Ubuntu now.

Thanks @pramitchoudhary for reporting this one!
